name = "ARTime"
uuid = "9badb8af-59cb-4d48-a775-3f35cfcfd143"
version = "0.1.0"
authors = ["Devesh Jawla"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
LinearAlgebra = "1.12.0"
Plots = "1.41.4"
Random = "1.11.0"
